'use client';
import Link from 'next/link';
import { useState } from 'react';
import { createDealAction } from '@/server/actions/sales';
import { PipelineKanban } from './PipelineKanban';
export function DealsView({ deals, pipelines, members, initialSearch }: { deals: any[]; pipelines: any[]; members: any[]; initialSearch: string }) {
  const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [view, setView] = useState<'table' | 'kanban'>('kanban'); const pipeline = pipelines.find(x => x.isDefault && x.isActive) || pipelines.find(x => x.isActive) || pipelines[0]; const stage = pipeline?.stages?.find((x: any) => x.isActive) || pipeline?.stages?.[0];
  async function create() { if (!pipeline || !stage || !members[0]) return setMessage('Create a pipeline and active member first'); const r = await createDealAction({ title, pipelineId: pipeline.id, stageId: stage.id, ownerId: members[0].id }); if (r.success) { setTitle(''); setMessage('Deal created'); window.location.reload(); } else setMessage(r.error || 'Unable to create deal'); }
  return <main className="p-6 space-y-6"><div><h1 className="text-2xl font-bold">Deals</h1><p className="text-sm text-slate-500">Track opportunities through organization-configured pipelines.</p></div><form action="/deals" className="flex flex-wrap gap-2"><input name="search" defaultValue={initialSearch} placeholder="Search deals" className="rounded border px-3 py-2" /><button className="rounded border px-4 py-2">Search</button><button type="button" onClick={() => setView(view === 'kanban' ? 'table' : 'kanban')} className="rounded border px-4 py-2">{view === 'kanban' ? 'Table view' : 'Kanban view'}</button></form><div className="flex gap-2"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="New deal title" className="rounded border px-3 py-2" /><button onClick={create} disabled={!title.trim()} className="rounded bg-brand-600 px-4 py-2 text-white">Create deal</button>{message && <span className="self-center text-sm">{message}</span>}</div>{view === 'kanban' ? <PipelineKanban deals={deals} pipeline={pipeline} /> : <div className="overflow-x-auto rounded border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Title</th><th className="p-3">Client</th><th className="p-3">Pipeline</th><th className="p-3">Stage</th><th className="p-3">Owner</th></tr></thead><tbody>{deals.map(d => <tr key={d.id} className="border-b"><td className="p-3 font-medium"><Link className="text-brand-600" href={`/deals/${d.id}`}>{d.title}</Link></td><td className="p-3">{d.client?.name || '—'}</td><td className="p-3">{d.pipeline?.name}</td><td className="p-3">{d.stage?.name}</td><td className="p-3">{d.owner?.name}</td></tr>)}</tbody></table></div>}</main>;
}
