'use server';

import { requireAuth } from '@/lib/auth/session';
import { hasPermission, PERMISSIONS } from '@/lib/permissions';
import { CustomFieldService, CustomFieldEntity, CustomFieldType } from '@/server/services/CustomFieldService';
import { OrganizationConfigService } from '@/server/services/OrganizationConfigService';
import { revalidatePath } from 'next/cache';

function guard(user: Awaited<ReturnType<typeof requireAuth>>, permission: string) { if (!hasPermission(user, permission)) throw new Error('Forbidden'); }
export async function getConfigurationAction() { try { const user = await requireAuth(); guard(user, PERMISSIONS.ORGANIZATION_SETTINGS_VIEW); return { success: true, config: await OrganizationConfigService.get(user), fields: await CustomFieldService.listDefinitions(user) }; } catch (e: any) { return { success: false, error: e.message || 'Unable to load configuration' }; } }
export async function createCustomFieldAction(input: { entityType: CustomFieldEntity; key: string; label: string; description?: string; fieldType: CustomFieldType; required?: boolean; searchable?: boolean; options?: unknown }) { try { const user = await requireAuth(); guard(user, PERMISSIONS.CUSTOM_FIELDS_CREATE); const field = await CustomFieldService.createDefinition(user, input); revalidatePath('/settings'); return { success: true, field }; } catch (e: any) { return { success: false, error: e.message || 'Unable to create custom field' }; } }
export async function updateCustomFieldAction(id: string, input: Parameters<typeof CustomFieldService.updateDefinition>[2]) { try { const user = await requireAuth(); guard(user, PERMISSIONS.CUSTOM_FIELDS_UPDATE); const field = await CustomFieldService.updateDefinition(user, id, input); revalidatePath('/settings'); return { success: true, field }; } catch (e: any) { return { success: false, error: e.message || 'Unable to update custom field' }; } }
export async function archiveCustomFieldAction(id: string) { try { const user = await requireAuth(); guard(user, PERMISSIONS.CUSTOM_FIELDS_DELETE); const field = await CustomFieldService.archiveDefinition(user, id); revalidatePath('/settings'); return { success: true, field }; } catch (e: any) { return { success: false, error: e.message || 'Unable to archive custom field' }; } }
export async function updateOrganizationConfigurationAction(input: Parameters<typeof OrganizationConfigService.updateOrganization>[1]) { try { const user = await requireAuth(); guard(user, PERMISSIONS.ORGANIZATION_SETTINGS_MANAGE); await OrganizationConfigService.updateOrganization(user, input); revalidatePath('/settings'); return { success: true }; } catch (e: any) { return { success: false, error: e.message || 'Unable to update organization settings' }; } }
export async function updateOrganizationListsAction(input: Parameters<typeof OrganizationConfigService.updateLists>[1]) { try { const user = await requireAuth(); guard(user, PERMISSIONS.ORGANIZATION_SETTINGS_MANAGE); await OrganizationConfigService.updateLists(user, input); revalidatePath('/settings'); return { success: true }; } catch (e: any) { return { success: false, error: e.message || 'Unable to update organization configuration' }; } }
