'use server';

import { requireAuth } from '@/lib/auth/session';
import { hasPermission, PERMISSIONS } from '@/lib/permissions';
import { LeadService, LeadConversionInput } from '@/server/services/LeadService';
import { DealService, DealInput } from '@/server/services/DealService';
import { PipelineService, PipelineInput, StageInput } from '@/server/services/PipelineService';
import { CrmTaskService, CrmTaskInput } from '@/server/services/CrmTaskService';
import { revalidatePath } from 'next/cache';

function requirePermission(user: Awaited<ReturnType<typeof requireAuth>>, permission: string) { if (!hasPermission(user, permission)) throw new Error('Forbidden'); }

export async function findLeadConversionDuplicatesAction(id: string) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.SCHOOLS_VIEW); return { success: true, duplicates: await LeadService.findConversionDuplicates(user, id) }; } catch (err: any) { return { success: false, error: err.message || 'Unable to check duplicates' }; } }
export async function convertLeadAction(id: string, input: LeadConversionInput) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.SCHOOLS_UPDATE); const result = await LeadService.convert(user, id, input); revalidatePath('/clients'); revalidatePath('/leads'); revalidatePath(`/leads/${id}`); return { success: true, result }; } catch (err: any) { return { success: false, error: err.message || 'Unable to convert lead' }; } }

export async function listPipelinesAction() { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.PIPELINES_VIEW); return { success: true, pipelines: await PipelineService.list(user) }; } catch (err: any) { return { success: false, error: err.message || 'Unable to list pipelines' }; } }
export async function createPipelineAction(input: PipelineInput) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.PIPELINES_MANAGE); const pipeline = await PipelineService.create(user, input); revalidatePath('/pipelines'); return { success: true, pipeline }; } catch (err: any) { return { success: false, error: err.message || 'Unable to create pipeline' }; } }
export async function updatePipelineAction(id: string, input: Partial<PipelineInput>) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.PIPELINES_MANAGE); const pipeline = await PipelineService.update(user, id, input); revalidatePath('/pipelines'); return { success: true, pipeline }; } catch (err: any) { return { success: false, error: err.message || 'Unable to update pipeline' }; } }
export async function createPipelineStageAction(pipelineId: string, input: StageInput) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.PIPELINES_MANAGE); const stage = await PipelineService.createStage(user, pipelineId, input); revalidatePath('/pipelines'); return { success: true, stage }; } catch (err: any) { return { success: false, error: err.message || 'Unable to create stage' }; } }
export async function updatePipelineStageAction(id: string, input: Partial<StageInput>) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.PIPELINES_MANAGE); const stage = await PipelineService.updateStage(user, id, input); revalidatePath('/pipelines'); return { success: true, stage }; } catch (err: any) { return { success: false, error: err.message || 'Unable to update stage' }; } }
export async function deactivatePipelineStageAction(id: string) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.PIPELINES_MANAGE); const stage = await PipelineService.deactivateStage(user, id); revalidatePath('/pipelines'); return { success: true, stage }; } catch (err: any) { return { success: false, error: err.message || 'Unable to deactivate stage' }; } }

export async function listDealsAction(filter?: Parameters<typeof DealService.list>[1]) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.DEALS_VIEW); return { success: true, deals: await DealService.list(user, filter) }; } catch (err: any) { return { success: false, error: err.message || 'Unable to list deals' }; } }
export async function getDealAction(id: string) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.DEALS_VIEW); return { success: true, deal: await DealService.get(user, id) }; } catch (err: any) { return { success: false, error: err.message || 'Unable to load deal' }; } }
export async function createDealAction(input: DealInput) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.DEALS_CREATE); const deal = await DealService.create(user, input); revalidatePath('/deals'); return { success: true, deal }; } catch (err: any) { return { success: false, error: err.message || 'Unable to create deal' }; } }
export async function updateDealAction(id: string, input: Partial<DealInput>) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.DEALS_UPDATE); const deal = await DealService.update(user, id, input); revalidatePath('/deals'); revalidatePath(`/deals/${id}`); return { success: true, deal }; } catch (err: any) { return { success: false, error: err.message || 'Unable to update deal' }; } }
export async function deleteDealAction(id: string) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.DEALS_DELETE); await DealService.delete(user, id); revalidatePath('/deals'); return { success: true }; } catch (err: any) { return { success: false, error: err.message || 'Unable to archive deal' }; } }

export async function listCrmTasksAction(filter?: Parameters<typeof CrmTaskService.list>[1]) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.TASKS_VIEW); return { success: true, tasks: await CrmTaskService.list(user, filter) }; } catch (err: any) { return { success: false, error: err.message || 'Unable to list tasks' }; } }
export async function getCrmTaskAction(id: string) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.TASKS_VIEW); return { success: true, task: await CrmTaskService.get(user, id) }; } catch (err: any) { return { success: false, error: err.message || 'Unable to load task' }; } }
export async function createCrmTaskAction(input: CrmTaskInput) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.TASKS_CREATE); const task = await CrmTaskService.create(user, input); revalidatePath('/tasks'); return { success: true, task }; } catch (err: any) { return { success: false, error: err.message || 'Unable to create task' }; } }
export async function updateCrmTaskAction(id: string, input: Partial<CrmTaskInput>) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.TASKS_UPDATE); const task = await CrmTaskService.update(user, id, input); revalidatePath('/tasks'); return { success: true, task }; } catch (err: any) { return { success: false, error: err.message || 'Unable to update task' }; } }
export async function deleteCrmTaskAction(id: string) { try { const user = await requireAuth(); requirePermission(user, PERMISSIONS.TASKS_DELETE); await CrmTaskService.delete(user, id); revalidatePath('/tasks'); return { success: true }; } catch (err: any) { return { success: false, error: err.message || 'Unable to archive task' }; } }
