'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useI18n } from '@/lib/i18n/context';
import { createTicketAction } from '@/server/actions/tickets';
import { Modal } from '@/components/ui/Modal';

interface TicketFormModalProps { isOpen: boolean; onClose: () => void; schools?: { id: string; name: string }[]; taskTypes?: { id: string; name: string }[]; users?: { id: string; name: string; email: string; department?: { name: string } | null }[]; managerName?: string | null; }
export function TicketFormModal({ isOpen, onClose, schools = [], taskTypes = [], users = [] }: TicketFormModalProps) {
  const { t, language } = useI18n(); const router = useRouter(); const [assignedToUserId, setAssignedToUserId] = useState(''); const [schoolId, setSchoolId] = useState(''); const [taskTypeId, setTaskTypeId] = useState(''); const [subject, setSubject] = useState(''); const [priority, setPriority] = useState('MEDIUM'); const [dueDate, setDueDate] = useState(''); const [initialNote, setInitialNote] = useState(''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!assignedToUserId || subject.trim().length < 3) { setError(t('common.error')); return; } setLoading(true); const result = await createTicketAction({ assignedToUserId, schoolId: schoolId || null, taskTypeId: taskTypeId || null, subject: subject.trim(), priority: priority as any, dueDate: dueDate || null, initialNote: initialNote || null }); setLoading(false); if (!result.success) { setError(result.error || t('common.error')); return; } onClose(); router.refresh(); if (result.ticketId) router.push(`/tickets/${result.ticketId}`); }
  return <Modal isOpen={isOpen} onClose={onClose} title={t('tickets.createTicket')} description={t('tickets.allTicketsSubtitle')} maxWidth="lg"><form onSubmit={submit} className="space-y-4"><div>{error && <p className="text-xs text-rose-600">{error}</p>}<label className="block text-xs font-bold">{language === 'ar' ? 'Assign To' : 'Assign To'} *</label><select required value={assignedToUserId} onChange={e => setAssignedToUserId(e.target.value)} className="w-full p-2.5 rounded-xl border text-xs"><option value="">{language === 'ar' ? 'Select eligible team member' : 'Select an eligible team member'}</option>{users.map(u => <option key={u.id} value={u.id}>{u.name}{u.department ? ` (${u.department.name})` : ''}</option>)}</select><p className="text-[11px] text-slate-500">Authorization is enforced server-side.</p></div><div className="grid grid-cols-2 gap-3"><select value={schoolId} onChange={e => setSchoolId(e.target.value)} className="w-full p-2.5 rounded-xl border text-xs"><option value="">School (optional)</option>{schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={taskTypeId} onChange={e => setTaskTypeId(e.target.value)} className="w-full p-2.5 rounded-xl border text-xs"><option value="">Task type (optional)</option>{taskTypes.map(ti => <option key={ti.id} value={ti.id}>{ti.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><select value={priority} onChange={e => setPriority(e.target.value)} className="w-full p-2.5 rounded-xl border text-xs"><option value="LOW">{t('tickets.priorityLow')}</option><option value="MEDIUM">{t('tickets.priorityMedium')}</option><option value="HIGH">{t('tickets.priorityHigh')}</option><option value="URGENT">{t('tickets.priorityUrgent')}</option></select><input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} className="w-full p-2.5 rounded-xl border text-xs" /></div><input required minLength={3} value={subject} onChange={e => setSubject(e.target.value)} placeholder={t('tickets.descriptionLabel')} className="w-full p-2.5 rounded-xl border text-xs" /><textarea rows={3} value={initialNote} onChange={e => setInitialNote(e.target.value)} placeholder={t('tickets.typeYourNote')} className="w-full p-2.5 rounded-xl border text-xs" /><div className="flex justify-end gap-2"><button type="button" onClick={onClose}>{t('common.cancel')}</button><button type="submit" disabled={loading || !assignedToUserId} className="px-4 py-2 rounded-xl bg-brand-600 text-white text-xs">{loading ? t('common.loading') : t('tickets.createTicket')}</button></div></form></Modal>;
}
