'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { loginAction } from '@/server/actions/auth';
import { useI18n } from '@/lib/i18n/context';
import { LanguageSwitcher } from '@/components/layout/LanguageSwitcher';
import { ThemeToggle } from '@/components/layout/ThemeToggle';
import { Lock, Mail, AlertCircle, ArrowRight, Eye, EyeOff } from 'lucide-react';

export default function LoginPage() {
  const { t } = useI18n(); const router = useRouter();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState<string | null>(null); const [expired, setExpired] = useState(false);
  useEffect(() => setExpired(new URLSearchParams(window.location.search).get('expired') === '1'), []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(null); const result = await loginAction({ email, password }); setLoading(false); if (result.success) { router.push('/'); router.refresh(); } else setError(result.error || t('auth.invalidCredentials')); };
  return <div className="min-h-screen bg-background dark:bg-slate-950 flex flex-col justify-between p-4 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3 max-w-5xl mx-auto w-full"><div className="flex items-center gap-3 min-w-0"><div className="w-10 h-10 shrink-0 rounded-2xl bg-brand-600 flex items-center justify-center text-white font-black text-xl">CL</div><div className="min-w-0"><h1 className="font-bold text-lg text-slate-900 dark:text-white truncate">{t('app.title')}</h1><p className="text-xs text-brand-600 truncate">{t('app.subtitle')}</p></div></div><div className="flex items-center gap-2 shrink-0"><LanguageSwitcher /><ThemeToggle /></div></div><div className="w-full max-w-md mx-auto my-8 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-8 shadow-xl space-y-6"><div className="text-center space-y-1"><h2 className="text-2xl font-black text-slate-900 dark:text-slate-100">{t('auth.loginTitle')}</h2><p className="text-xs text-slate-500">{t('auth.loginSubtitle')}</p></div>{(expired || error) && <div className="p-3 bg-rose-50 rounded-xl text-rose-700 text-xs flex items-center gap-2"><AlertCircle className="w-4 h-4" /><span>{error || t('auth.sessionExpired')}</span></div>}<form onSubmit={submit} className="space-y-4"><label className="block text-xs font-bold">{t('auth.email')}<div className="relative mt-1"><Mail className="absolute start-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder={t('auth.emailPlaceholder')} className="w-full ps-9 py-2.5 rounded-xl border bg-white dark:bg-slate-800 text-sm" /></div></label><label className="block text-xs font-bold">{t('auth.password')}<div className="relative mt-1"><Lock className="absolute start-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input required type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t('auth.passwordPlaceholder')} className="w-full ps-9 pe-10 py-2.5 rounded-xl border bg-white dark:bg-slate-800 text-sm" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute end-1 top-1/2 -translate-y-1/2 p-2 rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div></label><button disabled={loading} className="w-full flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-bold text-white bg-brand-600 disabled:opacity-50">{loading ? t('auth.signingIn') : t('auth.signIn')}<ArrowRight className="w-4 h-4 rtl:rotate-180" /></button></form><div className="text-center"><Link href="/forgot-password" className="text-xs font-bold text-brand-600">{t('auth.forgotPassword')}</Link></div></div><div className="text-center text-xs text-slate-400">{t('app.copyright')}</div></div>;
}
