-- Transitional ownership migration. Every existing business row is mapped to
-- the single legacy organization created by the previous migration. Columns
-- remain nullable for this migration so existing write paths keep working;
-- application scoping and a later NOT NULL migration must follow.

ALTER TABLE "Department" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "School" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "SchoolResearchJob" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "SchoolApprovalRequest" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "TicketApprovalRequest" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "ChatConversation" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "SchoolAssignment" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "TaskType" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "Ticket" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "Attachment" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "Notification" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "ActivityEvent" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "Todo" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "Message" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "MessageAttachment" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "CalendarEvent" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "MessageTemplate" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "ProposalTemplate" ADD COLUMN "organizationId" TEXT;
ALTER TABLE "Proposal" ADD COLUMN "organizationId" TEXT;

UPDATE "Department" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "School" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "SchoolResearchJob" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "SchoolApprovalRequest" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "TicketApprovalRequest" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "ChatConversation" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "SchoolAssignment" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "TaskType" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "Ticket" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "Attachment" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "Notification" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "AuditLog" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "ActivityEvent" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "Todo" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "Message" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "MessageAttachment" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "CalendarEvent" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "MessageTemplate" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "ProposalTemplate" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;
UPDATE "Proposal" SET "organizationId" = 'org_codeline_legacy' WHERE "organizationId" IS NULL;

ALTER TABLE "Department" ADD CONSTRAINT "Department_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "School" ADD CONSTRAINT "School_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SchoolResearchJob" ADD CONSTRAINT "SchoolResearchJob_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SchoolApprovalRequest" ADD CONSTRAINT "SchoolApprovalRequest_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TicketApprovalRequest" ADD CONSTRAINT "TicketApprovalRequest_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ChatConversation" ADD CONSTRAINT "ChatConversation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SchoolAssignment" ADD CONSTRAINT "SchoolAssignment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TaskType" ADD CONSTRAINT "TaskType_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ActivityEvent" ADD CONSTRAINT "ActivityEvent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Todo" ADD CONSTRAINT "Todo_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MessageAttachment" ADD CONSTRAINT "MessageAttachment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MessageTemplate" ADD CONSTRAINT "MessageTemplate_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProposalTemplate" ADD CONSTRAINT "ProposalTemplate_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Proposal" ADD CONSTRAINT "Proposal_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "Department_organizationId_idx" ON "Department"("organizationId");
CREATE INDEX "School_organizationId_status_idx" ON "School"("organizationId", "status");
CREATE INDEX "SchoolResearchJob_organizationId_createdAt_idx" ON "SchoolResearchJob"("organizationId", "createdAt");
CREATE INDEX "SchoolApprovalRequest_organizationId_status_idx" ON "SchoolApprovalRequest"("organizationId", "status");
CREATE INDEX "TicketApprovalRequest_organizationId_status_idx" ON "TicketApprovalRequest"("organizationId", "status");
CREATE INDEX "ChatConversation_organizationId_updatedAt_idx" ON "ChatConversation"("organizationId", "updatedAt");
CREATE INDEX "SchoolAssignment_organizationId_createdAt_idx" ON "SchoolAssignment"("organizationId", "createdAt");
CREATE INDEX "TaskType_organizationId_isActive_idx" ON "TaskType"("organizationId", "isActive");
CREATE INDEX "Ticket_organizationId_status_idx" ON "Ticket"("organizationId", "status");
CREATE INDEX "Ticket_organizationId_createdAt_idx" ON "Ticket"("organizationId", "createdAt");
CREATE INDEX "Attachment_organizationId_createdAt_idx" ON "Attachment"("organizationId", "createdAt");
CREATE INDEX "Notification_organizationId_createdAt_idx" ON "Notification"("organizationId", "createdAt");
CREATE INDEX "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId", "createdAt");
CREATE INDEX "ActivityEvent_organizationId_createdAt_idx" ON "ActivityEvent"("organizationId", "createdAt");
CREATE INDEX "Todo_organizationId_createdAt_idx" ON "Todo"("organizationId", "createdAt");
CREATE INDEX "Message_organizationId_createdAt_idx" ON "Message"("organizationId", "createdAt");
CREATE INDEX "MessageAttachment_organizationId_createdAt_idx" ON "MessageAttachment"("organizationId", "createdAt");
CREATE INDEX "CalendarEvent_organizationId_startDate_idx" ON "CalendarEvent"("organizationId", "startDate");
CREATE INDEX "MessageTemplate_organizationId_isActive_idx" ON "MessageTemplate"("organizationId", "isActive");
CREATE INDEX "ProposalTemplate_organizationId_isActive_idx" ON "ProposalTemplate"("organizationId", "isActive");
CREATE INDEX "Proposal_organizationId_status_idx" ON "Proposal"("organizationId", "status");
CREATE INDEX "Proposal_organizationId_createdAt_idx" ON "Proposal"("organizationId", "createdAt");
