import prisma from '@/lib/db/prisma';
import { UserSession } from '@/types';
import { requireOrganizationContext } from '@/lib/auth/organization';
import { AuditService } from './AuditService';
import { CustomFieldService } from './CustomFieldService';

export interface ContactInput { clientId?: string | null; firstName: string; lastName?: string | null; jobTitle?: string | null; email?: string | null; phone?: string | null; mobile?: string | null; isPrimary?: boolean; notes?: string | null; assignedUserId?: string | null; customFields?: Record<string, unknown>; }
const clean = (value?: string | null) => value?.trim() || null;

export class ContactService {
  private static async validateRelations(organizationId: string, input: ContactInput) {
    if (input.clientId && !(await prisma.client.findFirst({ where: { id: input.clientId, organizationId, deletedAt: null }, select: { id: true } }))) throw new Error('Client not found in the active organization');
    if (input.assignedUserId && !(await prisma.organizationMember.findFirst({ where: { organizationId, userId: input.assignedUserId, status: 'ACTIVE' }, select: { id: true } }))) throw new Error('Assigned user is not in the active organization');
  }
  static async list(user: UserSession, filter: { search?: string; clientId?: string } = {}) { const organizationId = (await requireOrganizationContext(user)).id; const where: any = { organizationId, deletedAt: null, ...(filter.clientId ? { clientId: filter.clientId } : {}) }; if (filter.search?.trim()) { const q = filter.search.trim(); where.OR = [{ firstName: { contains: q, mode: 'insensitive' } }, { lastName: { contains: q, mode: 'insensitive' } }, { email: { contains: q, mode: 'insensitive' } }, { phone: { contains: q, mode: 'insensitive' } }]; } return prisma.contact.findMany({ where, orderBy: [{ isPrimary: 'desc' }, { createdAt: 'desc' }], include: { client: true, assignedUser: { select: { id: true, name: true, email: true } } } }); }
  static async get(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; return prisma.contact.findFirst({ where: { id, organizationId, deletedAt: null }, include: { client: true, assignedUser: true, deals: { where: { deletedAt: null }, include: { pipeline: true, stage: true } }, crmTasks: { where: { deletedAt: null }, orderBy: { dueDate: 'asc' } } } }); }
  static async create(user: UserSession, input: ContactInput) { const organizationId = (await requireOrganizationContext(user)).id; if (!input.firstName?.trim()) throw new Error('Contact first name is required'); await this.validateRelations(organizationId, input); const contact = await prisma.contact.create({ data: { organizationId, clientId: input.clientId || null, firstName: input.firstName.trim(), lastName: clean(input.lastName), jobTitle: clean(input.jobTitle), email: clean(input.email), phone: clean(input.phone), mobile: clean(input.mobile), isPrimary: !!input.isPrimary, notes: clean(input.notes), assignedUserId: input.assignedUserId || null } }); if (input.customFields) await CustomFieldService.setValues(user, 'CONTACT', contact.id, input.customFields); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'CONTACT_CREATED', entityType: 'Contact', entityId: contact.id }); return contact; }
  static async update(user: UserSession, id: string, input: Partial<ContactInput>) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.contact.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw new Error('Contact not found'); await this.validateRelations(organizationId, input as ContactInput); const data: any = {}; for (const key of ['firstName', 'lastName', 'jobTitle', 'email', 'phone', 'mobile', 'notes', 'clientId', 'assignedUserId'] as const) if (input[key] !== undefined) data[key] = typeof input[key] === 'string' ? clean(input[key]) : input[key]; if (input.isPrimary !== undefined) data.isPrimary = input.isPrimary; const contact = await prisma.contact.update({ where: { id }, data }); if (input.customFields) await CustomFieldService.setValues(user, 'CONTACT', id, input.customFields); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'CONTACT_UPDATED', entityType: 'Contact', entityId: id }); return contact; }
  static async delete(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.contact.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw new Error('Contact not found'); return prisma.contact.update({ where: { id }, data: { deletedAt: new Date() } }); }
}
