import prisma from '@/lib/db/prisma';
import { UserSession } from '@/types';
import { requireOrganizationContext } from '@/lib/auth/organization';
import { AuditService } from './AuditService';
import { CustomFieldService } from './CustomFieldService';
import { WorkflowService } from './WorkflowService';

export interface CrmTaskInput { title: string; description?: string | null; status?: string; priority?: string; dueDate?: string | null; ownerId?: string | null; assignedUserId?: string | null; assignedTeamId?: string | null; clientId?: string | null; leadId?: string | null; contactId?: string | null; dealId?: string | null; ticketId?: string | null; customFields?: Record<string, unknown>; }
export class CrmTaskService {
  private static async relations(organizationId: string, input: CrmTaskInput) { const checks = [input.clientId ? prisma.client.findFirst({ where: { id: input.clientId, organizationId, deletedAt: null }, select: { id: true } }) : null, input.leadId ? prisma.lead.findFirst({ where: { id: input.leadId, organizationId, deletedAt: null }, select: { id: true } }) : null, input.contactId ? prisma.contact.findFirst({ where: { id: input.contactId, organizationId, deletedAt: null }, select: { id: true } }) : null, input.dealId ? prisma.deal.findFirst({ where: { id: input.dealId, organizationId, deletedAt: null }, select: { id: true } }) : null, input.ticketId ? prisma.ticket.findFirst({ where: { id: input.ticketId, organizationId }, select: { id: true } }) : null]; const names = ['Client', 'Lead', 'Contact', 'Deal', 'Ticket']; const results = await Promise.all(checks); results.forEach((result, index) => { if ((checks[index] && !result)) throw new Error(`${names[index]} does not belong to the active organization`); }); const userIds = [input.ownerId, input.assignedUserId].filter(Boolean) as string[]; if (userIds.length && await prisma.organizationMember.count({ where: { organizationId, userId: { in: userIds }, status: 'ACTIVE' } }) !== new Set(userIds).size) throw new Error('Task user does not belong to the active organization'); if (input.assignedTeamId && !(await prisma.team.findFirst({ where: { id: input.assignedTeamId, organizationId, isActive: true }, select: { id: true } }))) throw new Error('Task team does not belong to the active organization'); }
  static async list(user: UserSession, filter: { status?: string; priority?: string; assignedUserId?: string; search?: string } = {}) { const organizationId = (await requireOrganizationContext(user)).id; const where: any = { organizationId, deletedAt: null, ...(filter.status ? { status: filter.status } : {}), ...(filter.priority ? { priority: filter.priority } : {}), ...(filter.assignedUserId ? { assignedUserId: filter.assignedUserId } : {}) }; if (filter.search?.trim()) where.OR = [{ title: { contains: filter.search.trim(), mode: 'insensitive' } }, { description: { contains: filter.search.trim(), mode: 'insensitive' } }]; return prisma.crmTask.findMany({ where, orderBy: [{ dueDate: 'asc' }, { createdAt: 'desc' }], include: { client: { select: { id: true, name: true } }, lead: { select: { id: true, name: true } }, contact: { select: { id: true, firstName: true, lastName: true } }, deal: { select: { id: true, title: true } }, assignedUser: { select: { id: true, name: true, email: true } }, assignedTeam: { select: { id: true, name: true } } } }); }
  static async get(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; return prisma.crmTask.findFirst({ where: { id, organizationId, deletedAt: null }, include: { client: true, lead: true, contact: true, deal: true, ticket: true, assignedUser: true, assignedTeam: true } }); }
  static async create(user: UserSession, input: CrmTaskInput) { const organizationId = (await requireOrganizationContext(user)).id; if (!input.title?.trim()) throw new Error('Task title is required'); if (input.dueDate && Number.isNaN(new Date(input.dueDate).getTime())) throw new Error('Invalid task due date'); await this.relations(organizationId, input); const task = await prisma.crmTask.create({ data: { organizationId, title: input.title.trim(), description: input.description?.trim() || null, status: input.status || 'TODO', priority: input.priority || 'MEDIUM', dueDate: input.dueDate ? new Date(input.dueDate) : null, ownerId: input.ownerId || user.id, assignedUserId: input.assignedUserId || null, assignedTeamId: input.assignedTeamId || null, createdById: user.id, clientId: input.clientId || null, leadId: input.leadId || null, contactId: input.contactId || null, dealId: input.dealId || null, ticketId: input.ticketId || null } }); if (input.customFields) await CustomFieldService.setValues(user, 'TASK', task.id, input.customFields); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'TASK_CREATED', entityType: 'CrmTask', entityId: task.id }); void WorkflowService.dispatch({ eventId: `Task:${task.id}:RECORD_CREATED`, organizationId, entityType: 'TASK', entityId: task.id, eventType: 'TASK_CREATED', actorId: user.id }).catch(console.error); return task; }
  static async update(user: UserSession, id: string, input: Partial<CrmTaskInput>) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.crmTask.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw new Error('Task not found'); await this.relations(organizationId, { ...input, title: input.title || existing.title } as CrmTaskInput); const data: any = {}; for (const key of ['title','description','status','priority','ownerId','assignedUserId','assignedTeamId','clientId','leadId','contactId','dealId','ticketId'] as const) if (input[key] !== undefined) data[key] = typeof input[key] === 'string' ? input[key].trim() : input[key] || null; if (input.dueDate !== undefined) data.dueDate = input.dueDate ? new Date(input.dueDate) : null; if (input.status === 'COMPLETED' && existing.status !== 'COMPLETED') { data.completedAt = new Date(); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'TASK_COMPLETED', entityType: 'CrmTask', entityId: id }); } if (input.status === 'CANCELLED') data.cancelledAt = new Date(); const result = await prisma.crmTask.update({ where: { id }, data }); if (input.customFields) await CustomFieldService.setValues(user, 'TASK', id, input.customFields); return result; }
  static async delete(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.crmTask.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw new Error('Task not found'); return prisma.crmTask.update({ where: { id }, data: { deletedAt: new Date(), status: 'CANCELLED', cancelledAt: new Date() } }); }
}
