import prisma from '@/lib/db/prisma';
import { UserSession } from '@/types';
import { requireOrganizationContext } from '@/lib/auth/organization';
import { AuditService } from './AuditService';
import { CustomFieldService } from './CustomFieldService';
import { WorkflowService } from './WorkflowService';

export interface DealInput { title: string; description?: string | null; clientId?: string | null; primaryContactId?: string | null; leadId?: string | null; pipelineId: string; stageId: string; value?: number | string | null; currency?: string; probability?: number | null; expectedCloseDate?: string | null; ownerId: string; teamId?: string | null; assignedUserIds?: string[]; customFields?: Record<string, unknown>; }
export class DealService {
  private static async relations(organizationId: string, input: Partial<DealInput>) {
    if (input.clientId && !(await prisma.client.findFirst({ where: { id: input.clientId, organizationId, deletedAt: null }, select: { id: true } }))) throw new Error('Client does not belong to the active organization');
    if (input.primaryContactId && !(await prisma.contact.findFirst({ where: { id: input.primaryContactId, organizationId, deletedAt: null }, select: { id: true } }))) throw new Error('Contact does not belong to the active organization');
    if (input.leadId && !(await prisma.lead.findFirst({ where: { id: input.leadId, organizationId, deletedAt: null }, select: { id: true } }))) throw new Error('Lead does not belong to the active organization');
    if (input.ownerId && !(await prisma.organizationMember.findFirst({ where: { organizationId, userId: input.ownerId, status: 'ACTIVE' }, select: { id: true } }))) throw new Error('Owner is not in the active organization');
    if (input.teamId && !(await prisma.team.findFirst({ where: { id: input.teamId, organizationId, isActive: true }, select: { id: true } }))) throw new Error('Team does not belong to the active organization');
    if (input.assignedUserIds?.length && (await prisma.organizationMember.count({ where: { organizationId, userId: { in: input.assignedUserIds }, status: 'ACTIVE' } })) !== new Set(input.assignedUserIds).size) throw new Error('All deal assignees must belong to the active organization');
  }
  private static async pipelineStage(organizationId: string, pipelineId: string, stageId: string) { const stage = await prisma.pipelineStage.findFirst({ where: { id: stageId, pipelineId, organizationId, isActive: true }, select: { id: true, type: true, probability: true } }); if (!stage) throw new Error('Pipeline stage does not belong to the selected pipeline'); return stage; }
  static async list(user: UserSession, filter: { search?: string; pipelineId?: string; stageId?: string; status?: string; ownerId?: string } = {}) { const organizationId = (await requireOrganizationContext(user)).id; const where: any = { organizationId, deletedAt: null }; if (filter.pipelineId) where.pipelineId = filter.pipelineId; if (filter.stageId) where.stageId = filter.stageId; if (filter.status) where.status = filter.status; if (filter.ownerId) where.ownerId = filter.ownerId; if (filter.search?.trim()) { const q = filter.search.trim(); where.OR = [{ title: { contains: q, mode: 'insensitive' } }, { description: { contains: q, mode: 'insensitive' } }, { client: { name: { contains: q, mode: 'insensitive' } } }]; } return prisma.deal.findMany({ where, orderBy: { createdAt: 'desc' }, include: { client: { select: { id: true, name: true, type: true } }, primaryContact: true, lead: { select: { id: true, name: true } }, pipeline: { select: { id: true, name: true } }, stage: true, owner: { select: { id: true, name: true, email: true } }, team: true, assignments: { include: { user: { select: { id: true, name: true, email: true } } } } } }); }
  static async get(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; return prisma.deal.findFirst({ where: { id, organizationId, deletedAt: null }, include: { client: true, primaryContact: true, lead: true, pipeline: { include: { stages: true } }, stage: true, owner: true, team: true, assignments: { include: { user: true } }, tasks: { where: { deletedAt: null }, orderBy: { createdAt: 'desc' } } } }); }
  static async create(user: UserSession, input: DealInput) { const organizationId = (await requireOrganizationContext(user)).id; if (!input.title?.trim()) throw new Error('Deal title is required'); if (input.probability !== undefined && input.probability !== null && (input.probability < 0 || input.probability > 100)) throw new Error('Probability must be between 0 and 100'); await this.relations(organizationId, input); const stage = await this.pipelineStage(organizationId, input.pipelineId, input.stageId); const deal = await prisma.deal.create({ data: { organizationId, title: input.title.trim(), description: input.description?.trim() || null, clientId: input.clientId || null, primaryContactId: input.primaryContactId || null, leadId: input.leadId || null, pipelineId: input.pipelineId, stageId: input.stageId, status: stage.type === 'WON' ? 'WON' : stage.type === 'LOST' ? 'LOST' : 'OPEN', value: input.value === undefined || input.value === null ? null : input.value, currency: input.currency || (await prisma.organization.findUniqueOrThrow({ where: { id: organizationId }, select: { currency: true } })).currency, probability: input.probability ?? stage.probability, expectedCloseDate: input.expectedCloseDate ? new Date(input.expectedCloseDate) : null, ownerId: input.ownerId, teamId: input.teamId || null, createdById: user.id, assignments: input.assignedUserIds?.length ? { create: [...new Set(input.assignedUserIds)].map(userId => ({ userId })) } : undefined } }); if (input.customFields) await CustomFieldService.setValues(user, 'DEAL', deal.id, input.customFields); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'DEAL_CREATED', entityType: 'Deal', entityId: deal.id }); void WorkflowService.dispatch({ eventId: `Deal:${deal.id}:RECORD_CREATED`, organizationId, entityType: 'DEAL', entityId: deal.id, eventType: 'RECORD_CREATED', actorId: user.id }).catch(console.error); return this.get(user, deal.id); }
  static async update(user: UserSession, id: string, input: Partial<DealInput>) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.deal.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw new Error('Deal not found'); await this.relations(organizationId, { ...input, ownerId: input.ownerId || existing.ownerId }); const pipelineId = input.pipelineId || existing.pipelineId; const stageId = input.stageId || existing.stageId; const stage = await this.pipelineStage(organizationId, pipelineId, stageId); const data: any = {}; for (const key of ['title','description','clientId','primaryContactId','leadId','pipelineId','stageId','currency','ownerId','teamId'] as const) if (input[key] !== undefined) data[key] = typeof input[key] === 'string' ? input[key].trim() : input[key] || null; if (input.value !== undefined) data.value = input.value; if (input.probability !== undefined) { if (input.probability !== null && (input.probability < 0 || input.probability > 100)) throw new Error('Probability must be between 0 and 100'); data.probability = input.probability; } if (input.expectedCloseDate !== undefined) data.expectedCloseDate = input.expectedCloseDate ? new Date(input.expectedCloseDate) : null; if (input.stageId && input.stageId !== existing.stageId) { data.status = stage.type === 'WON' ? 'WON' : stage.type === 'LOST' ? 'LOST' : 'OPEN'; data.probability = input.probability ?? stage.probability; } const updated = await prisma.$transaction(async tx => { const result = await tx.deal.update({ where: { id }, data }); if (input.assignedUserIds) { await tx.dealAssignee.deleteMany({ where: { dealId: id } }); await tx.dealAssignee.createMany({ data: [...new Set(input.assignedUserIds)].map(userId => ({ dealId: id, userId })) }); } return result; }); if (input.customFields) await CustomFieldService.setValues(user, 'DEAL', id, input.customFields); if (input.stageId && input.stageId !== existing.stageId) await AuditService.logAudit({ actorId: user.id, organizationId, action: 'DEAL_STAGE_CHANGED', entityType: 'Deal', entityId: id, metadata: { oldStageId: existing.stageId, newStageId: input.stageId } }); else await AuditService.logAudit({ actorId: user.id, organizationId, action: 'DEAL_UPDATED', entityType: 'Deal', entityId: id }); return this.get(user, updated.id); }
  static async delete(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.deal.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!existing) throw new Error('Deal not found'); return prisma.deal.update({ where: { id }, data: { deletedAt: new Date(), status: 'LOST' } }); }
}
