import prisma from '@/lib/db/prisma';
import { UserSession } from '@/types';
import { requireOrganizationContext } from '@/lib/auth/organization';
import { AuditService } from './AuditService';

export interface PipelineInput { name: string; description?: string | null; isDefault?: boolean; isActive?: boolean; }
export interface StageInput { name: string; order?: number; probability?: number; type?: string; isActive?: boolean; }
export class PipelineService {
  static async list(user: UserSession) { const organizationId = (await requireOrganizationContext(user)).id; return prisma.pipeline.findMany({ where: { organizationId }, orderBy: { createdAt: 'asc' }, include: { stages: { orderBy: { order: 'asc' } }, _count: { select: { deals: true } } } }); }
  static async get(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; return prisma.pipeline.findFirst({ where: { id, organizationId }, include: { stages: { orderBy: { order: 'asc' } }, _count: { select: { deals: true } } } }); }
  static async create(user: UserSession, input: PipelineInput) { const organizationId = (await requireOrganizationContext(user)).id; if (!input.name?.trim()) throw new Error('Pipeline name is required'); const result = await prisma.$transaction(async tx => { if (input.isDefault) await tx.pipeline.updateMany({ where: { organizationId }, data: { isDefault: false } }); const pipeline = await tx.pipeline.create({ data: { organizationId, name: input.name.trim(), description: input.description?.trim() || null, isDefault: !!input.isDefault, isActive: input.isActive !== false } }); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'PIPELINE_CREATED', entityType: 'Pipeline', entityId: pipeline.id }); return pipeline; }); return result; }
  static async update(user: UserSession, id: string, input: Partial<PipelineInput>) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.pipeline.findFirst({ where: { id, organizationId } }); if (!existing) throw new Error('Pipeline not found'); return prisma.$transaction(async tx => { if (input.isDefault) await tx.pipeline.updateMany({ where: { organizationId, id: { not: id } }, data: { isDefault: false } }); const updated = await tx.pipeline.update({ where: { id }, data: { ...(input.name !== undefined ? { name: input.name.trim() } : {}), ...(input.description !== undefined ? { description: input.description?.trim() || null } : {}), ...(input.isDefault !== undefined ? { isDefault: input.isDefault } : {}), ...(input.isActive !== undefined ? { isActive: input.isActive } : {}) } }); await AuditService.logAudit({ actorId: user.id, organizationId, action: 'PIPELINE_UPDATED', entityType: 'Pipeline', entityId: id }); return updated; }); }
  static async deactivate(user: UserSession, id: string) { return this.update(user, id, { isActive: false }); }
  static async createStage(user: UserSession, pipelineId: string, input: StageInput) { const organizationId = (await requireOrganizationContext(user)).id; const pipeline = await prisma.pipeline.findFirst({ where: { id: pipelineId, organizationId } }); if (!pipeline) throw new Error('Pipeline not found'); const order = input.order ?? ((await prisma.pipelineStage.aggregate({ where: { pipelineId }, _max: { order: true } }))._max.order ?? -1) + 1; if (input.probability !== undefined && (input.probability < 0 || input.probability > 100)) throw new Error('Probability must be between 0 and 100'); return prisma.pipelineStage.create({ data: { organizationId, pipelineId, name: input.name.trim(), order, probability: input.probability ?? 0, type: input.type || 'OPEN', isActive: input.isActive !== false } }); }
  static async updateStage(user: UserSession, id: string, input: Partial<StageInput>) { const organizationId = (await requireOrganizationContext(user)).id; const stage = await prisma.pipelineStage.findFirst({ where: { id, organizationId } }); if (!stage) throw new Error('Pipeline stage not found'); if (input.probability !== undefined && (input.probability < 0 || input.probability > 100)) throw new Error('Probability must be between 0 and 100'); return prisma.pipelineStage.update({ where: { id }, data: { ...(input.name !== undefined ? { name: input.name.trim() } : {}), ...(input.order !== undefined ? { order: input.order } : {}), ...(input.probability !== undefined ? { probability: input.probability } : {}), ...(input.type !== undefined ? { type: input.type } : {}), ...(input.isActive !== undefined ? { isActive: input.isActive } : {}) } }); }
  static async deactivateStage(user: UserSession, id: string) { const organizationId = (await requireOrganizationContext(user)).id; const stage = await prisma.pipelineStage.findFirst({ where: { id, organizationId }, include: { _count: { select: { deals: true } } } }); if (!stage) throw new Error('Pipeline stage not found'); if (stage._count.deals) throw new Error('Move deals before deactivating a stage'); return prisma.pipelineStage.update({ where: { id }, data: { isActive: false } }); }
  static async ensureDefault(user: UserSession) { const organizationId = (await requireOrganizationContext(user)).id; const existing = await prisma.pipeline.findFirst({ where: { organizationId, isDefault: true, isActive: true } }); if (existing) return existing; const pipeline = await this.create(user, { name: 'Sales', isDefault: true }); for (const [order, name, type, probability] of [['0','New','OPEN',10],['1','Qualified','OPEN',25],['2','Meeting','OPEN',50],['3','Proposal','OPEN',70],['4','Negotiation','OPEN',85],['5','Won','WON',100],['6','Lost','LOST',0] ] as const) await this.createStage(user, pipeline.id, { name, order: Number(order), type, probability }); return this.get(user, pipeline.id); }
}
