'use client';

import { useI18n } from '@/lib/i18n/context';
import { useTheme } from 'next-themes';
import { Settings, Globe, Moon, Sun } from 'lucide-react';

export function SettingsClientView() {
  const { t, language, setLanguage } = useI18n();
  const { theme, setTheme } = useTheme();
  return <div className="max-w-3xl mx-auto space-y-6"><div><h2 className="text-xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2"><Settings className="w-5 h-5 text-brand-600" /><span>{t('settings.title')}</span></h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{t('settings.subtitle')}</p></div><div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6"><h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2"><Globe className="w-4 h-4 text-brand-600" /><span>{t('settings.preferences')}</span></h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/40 space-y-3"><label className="block text-xs font-bold text-slate-700 dark:text-slate-300">{t('settings.language')}</label><div className="flex items-center gap-2"><button type="button" onClick={() => setLanguage('ar')} className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold ${language === 'ar' ? 'bg-brand-600 text-white' : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700'}`}>العربية</button><button type="button" onClick={() => setLanguage('en')} className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold ${language === 'en' ? 'bg-brand-600 text-white' : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700'}`}>English</button></div></div><div className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/40 space-y-3"><label className="block text-xs font-bold text-slate-700 dark:text-slate-300">{t('settings.theme')}</label><div className="flex items-center gap-2"><button type="button" onClick={() => setTheme('light')} className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ${theme === 'light' ? 'bg-brand-600 text-white' : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700'}`}><Sun className="w-3.5 h-3.5" />{t('common.light')}</button><button type="button" onClick={() => setTheme('dark')} className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ${theme === 'dark' ? 'bg-brand-600 text-white' : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700'}`}><Moon className="w-3.5 h-3.5" />{t('common.dark')}</button></div></div></div></div></div>;
}
